version: '2'

services:
  zookeeper:
    image: 'docker.io/bitnami/zookeeper:3-debian-10'
    ports:
      - '2181:2181'
    # volumes:
    #   - 'zookeeper_data:/bitnami'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: 'docker.io/bitnami/kafka:2-debian-10'
    ports:
      - '9092:9092'
    # volumes:
    #   - 'kafka_data:/bitnami'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper


  producer:
    container_name: timeseries-producer
    image: 'node:12'
    volumes:
      - ./timeseries-producer:/home/task
    working_dir: /home/task
    command: node index.js
    depends_on:
      - kafka


  spark:
    image: docker.io/bitnami/spark:3-debian-10
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - '8080:8080'
    depends_on:
      - 'kafka'
    user: root
    volumes:
      - ./spark-regression:/opt/bitnami/spark/regression
    command: 'bin/spark-submit --packages org.apache.spark:spark-sql-kafka-0-10_2.12:3.0.0 regression/main.py kafka:9092 bitcoin'
  # spark-worker-1:
  #   build: ./spark-regression
  #   environment:
  #     - SPARK_MODE=worker
  #     - SPARK_MASTER_URL=spark://spark:7077
  #     - SPARK_WORKER_MEMORY=1G
  #     - SPARK_WORKER_CORES=1
  #     - SPARK_RPC_AUTHENTICATION_ENABLED=no
  #     - SPARK_RPC_ENCRYPTION_ENABLED=no
  #     - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
  #     - SPARK_SSL_ENABLED=no
  # spark-worker-2:
  #   build: ./spark-regression
  #   environment:
  #     - SPARK_MODE=worker
  #     - SPARK_MASTER_URL=spark://spark:7077
  #     - SPARK_WORKER_MEMORY=1G
  #     - SPARK_WORKER_CORES=1
  #     - SPARK_RPC_AUTHENTICATION_ENABLED=no
  #     - SPARK_RPC_ENCRYPTION_ENABLED=no
  #     - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
  #     - SPARK_SSL_ENABLED=no



  # consumer:
  #   container_name: regression-consumer
  #   image: 'node:12'
  #   volumes:
  #     - ./regression-consumer:/home/task
  #   working_dir: /home/task
  #   command: node index.js
  #   restart: on-failure
  #   depends_on:
  #     - kafka

# volumes:
#   zookeeper_data:
#     driver: local
#   kafka_data:
#     driver: local
