FROM python:3

RUN apt-get update && apt-get install -y \
    build-essential \
    libffi-dev \
    python-dev

ADD . /home

WORKDIR /home

RUN pip install kafka-python 
RUN pip install -r requirements.txt 